name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ] # Runs every time you push to main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x' # Match your project version

      - name: Publish App
        run: dotnet publish -c Release -o release

      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/MertikaOrthodoxPrayerHelper\/" \/>/g' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
